## Numpy 
This Note book will have references for all Numpy and related code practise

In [1]:
#import statement
import numpy as np

#### 1-D Array###
**Creating a 1-D Array**

There are several ways to create ndarrays in NumPy. The two ways to create ndarrays:

Using regular Python lists

Using built-in NumPy functions

In this section, we will create ndarrays by providing Python lists to the NumPy *np.array()* function. It is important to remember that np.array() is NOT a class, it is just a function that returns an ndarray

In [5]:
#Let's create a 1D array x
x= np.array([1,2,3,4,5])
print(x)



[1 2 3 4 5]


**Rank:**

1D arrays as rank 1 arrays. In general N-Dimensional arrays have rank N. 
Therefore, we refer to a 2D array as a rank 2 array. 

**Shape, Size and Datatype of Array:**

The shape of an array is the size along each of its dimensions. 
For example, the shape of a rank 2 array will correspond to the *number of rows and columns* of the array. 
The shape attribute returns a tuple of N positive integers that specify the sizes of each dimension. 
In the example below we will see the details of 1-D array created and its shape, its type, and the data-type (dtype) of its elements.

In [7]:
#print the shape of the array
print ("Shape of array: ", x.shape)

#print the size of the array
print ("Size of array: ",x.size)

#print the data type
print("Data type of array: ",x.dtype)

Shape of array:  (5,)
Size of array:  5
Data type of array:  int32


We can see that the shape attribute returns the tuple (5,) telling us that x is of rank 1 (i.e. x only has 1 dimension ) and it has 5 elements. 
The type() function tells us that x is indeed a NumPy ndarray. 
Finally, the .dtype attribute tells us that the elements of x are stored in memory as signed 64-bit integers. Another great advantage of NumPy is that it can handle more data-types than Python lists.

In [9]:
b=np.array(["Apple","Google","Microsoft"])

print()
print(b)
print()

#print the shape of the array
print ("Shape of array: ", b.shape)

#print the size of the array
print ("Size of array: ",b.size)

#print the data type
print("Data type of array: ",b.dtype)


['Apple' 'Google' 'Microsoft']

Shape of array:  (3,)
Size of array:  3
Data type of array:  <U9


dtype attribute tells us that the elements in b are stored in memory as Unicode strings of 5 characters.

#### 2-D Array ####

**Creating a 2D array**
2D array will have 2 dimension as row & columns

In [12]:
#lets us create  2D array
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print(y)
print()

#print the shape of the array
print ("Shape of array: ", y.shape)

#print the size of the array
print ("Size of array: ",y.size)

#print the data type
print("Data type of array element: ",y.dtype)

#print the type of array
print("Object type of array y:",type(y))



[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of array:  (3, 3)
Size of array:  9
Data type of array element:  int32
Object type of array y: <class 'numpy.ndarray'>


**Key notes**

- Numpy will store elements based on the value, if integer it store as int if float stores as float
- if we have both int and float in arrray, numpy will store the element as float. This is called **upcasting**

In [13]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


Even though NumPy automatically selects the dtype of the ndarray, NumPy also allows you to specify the particular dtype you want to assign to the elements of the ndarray. You can specify the dtype when you create the ndarray using the keyword dtype in the np.array() function. Let's see an example:

In [14]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print x
print()
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

The elements in x are of type: int64


**Save & Load Array to/from file**

In [15]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)


# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# We print y
print()
print('y = ', y)
print()

# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)


y =  [1 2 3 4 5]

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


#### Built-in-Functions ####

- np.zero(shape) - create zeros with give shape
- np.ones() - create ones with given shape, we can change the data type of elements by passing the dtype value
- np.full(shape, constant value) - create an ndarray with a specified shape that is full of any number we want

In [7]:
# We create a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

# We create a 3 x 3 ndarray full of ones. 
Y = np.ones((3,3), dtype=int)
# We print X
print()
print('Y = \n', Y)
print()

# We print information about X
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

#we create a full array
Z = np.full((3,4),5)

# We print Z
print()
print('Z = \n', Y)
print()

# We print information about Z
print('Z has dimensions:', Z.shape)
print('Z is an object of type:', type(Z))
print('The elements in Z are of type:', Z.dtype)



X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64

Y = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Y has dimensions: (3, 3)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32

Z = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Z has dimensions: (3, 4)
Z is an object of type: <class 'numpy.ndarray'>
The elements in Z are of type: int32


**Identity Matrix**

- As you will learn later, a fundamental array in Linear Algebra is the *Identity Matrix*.
- An Identity matrix is a square matrix that has only 1s in its main diagonal and zeros everywhere else. 
- The function np.eye(N) creates a square N x N ndarray corresponding to the Identity matrix. 
Since all Identity Matrices are square, the np.eye() function only takes a single integer as an argument

In [10]:
#creating a idenity matrix
X = np.eye(5)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)  


X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


**Diagonal Matrix**


In [11]:
y_diag = np.diag([10,15,20,25])
print(y_diag)


[[10  0  0  0]
 [ 0 15  0  0]
 [ 0  0 20  0]
 [ 0  0  0 25]]


**Arange**

- NumPy also allows you to create ndarrays that have evenly spaced values within a given interval. 
- NumPy's np.arange() function is very versatile and can be used with either one, two, or three arguments
- np.arange(N) i.e *np.arange(5)* - will create a rank 1 ndarray with consecutive integers between 0 and N - 1
- np.arange(start,stop) i.e *np.arange(1,10)* - will create a rank 1 ndarray with evenly spaced values within the half-open interval (start, stop). This means the evenly spaced numbers will **include start but exclude stop.**
- np.arrange(start,stop,step) i.e - np.arange(1,10,2) - will create a rank 1 ndarray with evenly spaced values within the half-open interval (start, stop) with *step* being the distance between two adjacent values

In [13]:
x= np.arange(10)
print(x)

x1 = np.arange(1,10)
print(x1)

x2 = np.arange(1,10,2)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


**Linspace**

Even though the np.arange() function allows for non-integer steps, such as 0.3, **the output is usually inconsistent, due to the finite floating point precision**. For this reason, in the cases where non-integer steps are required, it is usually better to use the function np.linspace()

 **np.linspace(start, stop, N)** function returns N evenly spaced numbers over the closed interval (start, stop). This means that both the start and thestop values are included

In [3]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25
X = np.linspace (0,25,10)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)  




X = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

X has dimensions: (10,)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


 - we can see 10 eventualy intervaled numbers between 0 to 25.
 - if need to exclude the last digit, we can by setting the keyword **endpoint = False**

**Reshape**

- np.reshape(ndarray, new_shape)
- Reshape used to convert the 1D to N-D array. 
- The elements in the 1D array shoud match the dimension we input. for example - 1D array with 10 elements can be reshaped as 2D with 5 x 2 or 2 x5 but not 3x4


In [7]:
x = np.arange(50)
print ("original X", x)
print ("shape of x", x.shape)

x=x.reshape(25,2)
print ("Reshaped X", x)
print ("shape of new x", x.shape)

original X [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
shape of x (50,)
Reshaped X [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]]
shape of new x (25, 2)


In [8]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 

# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32

X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


**Random Nd Arrays**

- **np.random.random(shape)** function to create an ndarray of the given shape with random floats in the half-open interval (0.0, 1.0)
- **np.random.randint(start, stop, size = shape)** creates an ndarray of the given shape with random integers in the half-open interval (start, stop)
- **np.random.rand(shape)** will create an array of the given shape and populate it with random samples from a uniform distribution over (0, 1)
- **np.random.normal(mean, standard deviation, size=shape)**
In some cases, you may need to create ndarrays with random numbers that satisfy certain statistical properties for example, creates an ndarray with the given shape that contains random numbers picked from a normal (Gaussian) distribution with the given mean and standard deviation. 
- **np.random.randn(N)** will generates a matrix filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1.

In [10]:
#np.random.random(shape)
X = np.random.random((3,3))
# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.95399281 0.01225931 0.31903071]
 [0.98280078 0.30819832 0.38684034]
 [0.36616898 0.3859594  0.35724233]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [11]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,(3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[ 4 12]
 [10 11]
 [11 13]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [13]:
#We create a 100 x 100 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0,0.1,(100,100))
# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[ 0.02694705  0.04947832 -0.03796749 ...  0.02729805  0.05198602
  -0.17310154]
 [ 0.05205792  0.02349479  0.26439026 ... -0.01095012  0.16664777
  -0.11486625]
 [-0.02468997  0.06961028 -0.03017137 ... -0.06069926 -0.0283256
   0.0976365 ]
 ...
 [ 0.12505832 -0.02593088  0.11265138 ...  0.21870188 -0.08361976
  -0.18012141]
 [ 0.11465266  0.04702692  0.03490346 ... -0.01316394  0.0086452
   0.11324408]
 [-0.01114407 -0.00139915 -0.00291159 ...  0.11343554  0.05561915
  -0.01782706]]

X has dimensions: (100, 100)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 0.0016703335992551331
The maximum value in X is: 0.40278695654831814
The minimum value in X is: -0.37163696787721756
X has 4923 negative numbers
X has 5077 positive numbers


In [14]:
#np.random.rand(shape)
X = np.random.rand(3,3)
# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.15434716 0.21688783 0.05244779]
 [0.83839356 0.56017946 0.79506465]
 [0.04089127 0.49589741 0.92745817]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [15]:
#np.random.randn(N)
X = np.random.randn(10)
# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [-0.46580439 -0.51769515 -1.36502286  0.12805296 -0.11770055  1.02629479
  0.41471195 -0.6559395  -1.30419416  1.04808341]

X has dimensions: (10,)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -0.1809213508641976
The maximum value in X is: 1.0480834144870415
The minimum value in X is: -1.3650228603895365
X has 6 negative numbers
X has 4 positive numbers


## Amending the data ##

**Index** 
- positive indices are used to access elements from the beginning of the array, while negative indices are used to access elements from the end of the array.
- To access elements in rank 2 ndarrays we need to provide 2 indices in the form (row, column)


In [6]:
x = np.arange(10)
print (x)
print("The first index {}".format(x[0]))
print("The third index {}".format(x[3]))
print("The last index {}".format(x[-1]))


[0 1 2 3 4 5 6 7 8 9]
The first index 0
The third index 3
The last index 9


In [7]:
#modify the value using the index
x[3] = 23
print(x)

[ 0  1  2 23  4  5  6  7  8  9]


In [11]:
x=np.arange(1,31).reshape(6,5)
print(x)
print (x.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
(6, 5)


In [13]:
# access the first col and first row using the row
# Let's access some elements in X
print('This is (0,0) Element in X:', x[0,0])
print('This is (0,1) Element in X:', x[0,1])
print('This is (2,2) Element in X:', x[2,2])

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 13


In [15]:
print()
print('Original:\n X = \n', x)
print()

# We change the (0,0) element in X from 1 to 20
x[0,0] = 20

# We print X after it was modified 
print('Modified:\n X = \n', x)


Original:
 X = 
 [[20  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

Modified:
 X = 
 [[20  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


**np.delete(ndarray, dimension, axis)**

- This function deletes the given list of elements from the given ndarray along the specified axis. 
- For rank 1 ndarrays the axis keyword is not required. 
- For rank 2 ndarrays, axis = 0 is used to select rows, and axis = 1 is used to select column

In [3]:
X = np.array([1,2,3,4,5])
Y = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print ("X:\n", X)
print ("Y:\n", Y)

X:
 [1 2 3 4 5]
Y:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# We delete the first and last element of x
v = np.delete(X,[0,4])
print (v)
# We delete the first row of y
u = np.delete(Y,0,axis=0)
# We delete the first & last col of y
u1 = np.delete(Y,[0,2], axis=1)

print (u)
print(u1)


[2 3 4]
[[4 5 6]
 [7 8 9]]
[[2]
 [5]
 [8]]


**np.append(ndarray, elements, axis)**
This function appends the given list of elements to ndarray along the specified axis

In [5]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

# We print x
print()
print('Original x = ', x)

# We append the integer 6 to x
x = np.append(x, 6)

# We print x
print()
print('x = ', x)

# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

# We print v
print()
print('v = \n', v)

# We print q
print()
print('q = \n', q)


Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]

Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


**np.insert(ndarray, index, elements, axis)** 
This function inserts the given list of elements to ndarray right before the given index along the specified axis

In [13]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# We create a rank 2 ndarray 
y = np.array([[1,2,3],[7,8,9]])

# We print x
print()
print('Original x = ', x)

#insert 3, 4 in X
x = np.insert(x,2,[3,4])

print("Modified X: ", x)

#insert 
y = np.insert(y,1,[[4,5,6]], axis=0)
print ("Modified Y:",y)

y = np.insert(y,3,[1,1,1], axis=1)
print ("Modified Y:",y)

# We insert a column full of 5s between the first and second column of y
v = np.insert(y,1,5, axis=1)
print (v)


Original x =  [1 2 5 6 7]
Modified X:  [1 2 3 4 5 6 7]
Modified Y: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified Y: [[1 2 3 1]
 [4 5 6 1]
 [7 8 9 1]]
[[1 5 2 3 1]
 [4 5 5 6 1]
 [7 5 8 9 1]]


NumPy also allows us to stack ndarrays on top of each other, or to stack them side by side. The stacking is done using either the np.vstack() function for vertical stacking, or the np.hstack() function for horizontal stacking. It is important to note that in order to stack ndarrays, the shape of the ndarrays must match. Let's see some examples:

In [15]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]


## Slicing ##

NumPy provides a way to access subsets of ndarrays. This is known as slicing. Slicing is performed by combining indices with the colon : symbol inside the square brackets. In general you will come across three types of slicing:

1. ndarray[start:end] - Is used to select elements between the start and end indices
2. ndarray[start:] - Is used to select all elements from the start index till the last index
3. ndarray[:end] - Is used to select all elements from the first index till the end index


In [17]:
X = np.arange(1,21).reshape(4,5)

print (X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [21]:
#slicing
print("Elements of X from 2nd row till last row, first two col:\n", X[1:,:2])

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)



Elements of X from 2nd row till last row, first two col:
 [[ 6  7]
 [11 12]
 [16 17]]
Z = 
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [23]:
# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)
# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)


v =  [11 12 13 14 15]

q =  [ 3  8 13 18]

R = 
 [[ 3]
 [ 8]
 [13]
 [18]]


**Slicing and assigning to new, variable is just creating a view. if we do changes to new variable it will affect the main array**

In [24]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]

# We print Z
print()
print('Z = \n', Z)
print()

# We change the last element in Z to 555
Z[2,2] = 555

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


X = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]



We can clearly see in the above example that if we make changes to Z, X changes as well

**np.copy()** function. The np.copy(ndarray) function creates a copy of the given ndarray. 

In [25]:
x = np.arange(1,31).reshape(6,5)
print ("X = \n", x)

X = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [32]:
z = np.copy(x[0:3,:3])
print (z)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [35]:
print (z.shape)
#chaning the 2,2 value in z
z[2,2]=77
print (z)
#changses in z doesn't affect the x
print(x)

(3, 3)
[[ 1  2  3]
 [ 6  7  8]
 [11 12 77]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [37]:
#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

# We change the last element in W to 444
W[2,2] = 444

# We print X
print()
print('X = \n', x)

# We print W
print()
print('W = \n', W)


X = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


In [38]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We create a rank 1 ndarray that will serve as indices to select elements from X
indices = np.array([1,3])

# We print X
print()
print('X = \n', X)
print()

# We print indices
print('indices = ', indices)
print()

# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]

# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]

# We print Y
print()
print('Y = \n', Y)

# We print Z
print()
print('Z = \n', Z)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

indices =  [1 3]


Y = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]

Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


**np.diag(ndarray, k=N)**: NumPy also offers built-in functions to select specific elements within ndarrays. 

- The np.diag(ndarray, k=N) function extracts the elements along the diagonal defined by N. 
- As default is k=0, which refers to the main diagonal. 
- Values of **k > 0** are used to select elements in diagonals **above** the main diagonal. 
- Values of **k < 0** are used to select elements in diagonals **below** the main diagonal. 

In [40]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('X = \n', X)
print()

# We print the elements in the main diagonal of X
print('z =', np.diag(X))
print()

# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=1))
print()

# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

z = [ 0  6 12 18 24]

y = [ 1  7 13 19]

w =  [ 5 11 17 23]


**np.unique():** The np.unique(ndarray) function returns the unique elements in the given ndarray.

In [46]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X
print()
print('X = \n', X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))
print('The count of unique elements in X are:', np.unique(X, return_counts=True))


X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in X are: [1 2 3 5 8]
The count of unique elements in X are: (array([1, 2, 3, 5, 8]), array([2, 3, 2, 1, 1], dtype=int64))


## Sorting & Bool Indexing ##

In [50]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [56]:
#print x > 10
print (x[x>10])
#print x less than 10
print(x[x<10])
#print x between 10 to 20
print(x[(x>10) & (x<20) ])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [57]:
# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X = np.copy(x)
X[(X > 10) & (X < 17)] = -1

# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



In addition to Boolean Indexing NumPy also allows for set operations. This useful when comparing ndarrays, for example, to find common elements between two ndarrays. Let's see some examples:

In [58]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


**np.sort()**
- np.sort() function to sort rank 1 and rank 2 ndarrays in different ways. 
- Like with other functions we saw before, the sort function can also be used as a method. 
- However, there is a big difference on how the data is stored in memory in this case. 
- **When np.sort() is used as a function ex. np.sort(x), it sorts the ndrrays out of place, meaning, that it doesn't change the original ndarray being sorted**.
- **when you use sort as a method, ndarray.sort() sorts ex: x.sort() the ndarray in place, meaning, that the original array will be changed to the sorted one.**

In [62]:
x = np.random.randint(1,10, size=(10,))
print("Original x: \n", x)

print ("The sorted array of x as function: \n", np.sort(x))
print("The unqiue values in sorted order :\n", np.sort(np.unique(x)))
print("Original x: \n", x)
print ("The sorted array of x as method: \n", x.sort())
print("x:\n", x)

Original x: 
 [6 5 8 2 4 1 6 7 9 9]
The sorted array of x as function: 
 [1 2 4 5 6 6 7 8 9 9]
The unqiue values in sorted order :
 [1 2 4 5 6 7 8 9]
Original x: 
 [6 5 8 2 4 1 6 7 9 9]
The sorted array of x as method: 
 None
x:
 [1 2 4 5 6 6 7 8 9 9]


When sorting rank 2 ndarrays, we need to specify to the np.sort() function whether we are sorting by rows or columns. This is done by using the axis keyword.

In [63]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original X = 
 [[ 2  2  3  2  9]
 [ 3  7  3  8  7]
 [10  1  1  5  4]
 [ 3  4  9  1  4]
 [ 8  4  6  7  5]]


X with sorted columns :
 [[ 2  1  1  1  4]
 [ 3  2  3  2  4]
 [ 3  4  3  5  5]
 [ 8  4  6  7  7]
 [10  7  9  8  9]]

X with sorted rows :
 [[ 2  2  2  3  9]
 [ 3  3  7  7  8]
 [ 1  1  4  5 10]
 [ 1  3  4  4  9]
 [ 4  5  6  7  8]]


## Arithmetic operations & Broadcasting ##

- [Broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)
- The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes

In [64]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)
print()


x =  [1 2 3 4]

y =  [5.5 6.5 7.5 8.5]



In [65]:
# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


In [66]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print()
print('X = \n', X)

# We print Y
print()
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))


X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


**Mathematical & Statistical functions**

In [67]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4])

# We print x
print()
print('x = ', x)

# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2


x =  [1 2 3 4]

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]


In [68]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


In [69]:
x = np.array([1,2,3])
print(np.cumsum(x))

[1 3 6]


NumPy can add single numbers to all the elements of an ndarray without the use of complicated loops.

In [70]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)


X = 
 [[1 2]
 [3 4]]

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]


In [71]:
# We create a rank 1 ndarray
x = np.array([1,2,3])

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

# We print x
print()
print('x = ', x)
print()

# We print Y
print()
print('Y = \n', Y)
print()

# We print Z
print()
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)



x =  [1 2 3]


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Z = 
 [[1]
 [2]
 [3]]

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
