## Numpy 
This Note book will have references for all Numpy and related code practise

In [4]:
#import statement
import numpy as np

#### 1-D Array###
**Creating a 1-D Array**

There are several ways to create ndarrays in NumPy. The two ways to create ndarrays:

Using regular Python lists

Using built-in NumPy functions

In this section, we will create ndarrays by providing Python lists to the NumPy *np.array()* function. It is important to remember that np.array() is NOT a class, it is just a function that returns an ndarray

In [5]:
#Let's create a 1D array x
x= np.array([1,2,3,4,5])
print(x)



[1 2 3 4 5]


**Rank:**

1D arrays as rank 1 arrays. In general N-Dimensional arrays have rank N. 
Therefore, we refer to a 2D array as a rank 2 array. 

**Shape, Size and Datatype of Array:**

The shape of an array is the size along each of its dimensions. 
For example, the shape of a rank 2 array will correspond to the *number of rows and columns* of the array. 
The shape attribute returns a tuple of N positive integers that specify the sizes of each dimension. 
In the example below we will see the details of 1-D array created and its shape, its type, and the data-type (dtype) of its elements.

In [7]:
#print the shape of the array
print ("Shape of array: ", x.shape)

#print the size of the array
print ("Size of array: ",x.size)

#print the data type
print("Data type of array: ",x.dtype)

Shape of array:  (5,)
Size of array:  5
Data type of array:  int32


We can see that the shape attribute returns the tuple (5,) telling us that x is of rank 1 (i.e. x only has 1 dimension ) and it has 5 elements. 
The type() function tells us that x is indeed a NumPy ndarray. 
Finally, the .dtype attribute tells us that the elements of x are stored in memory as signed 64-bit integers. Another great advantage of NumPy is that it can handle more data-types than Python lists.

In [9]:
b=np.array(["Apple","Google","Microsoft"])

print()
print(b)
print()

#print the shape of the array
print ("Shape of array: ", b.shape)

#print the size of the array
print ("Size of array: ",b.size)

#print the data type
print("Data type of array: ",b.dtype)


['Apple' 'Google' 'Microsoft']

Shape of array:  (3,)
Size of array:  3
Data type of array:  <U9


dtype attribute tells us that the elements in b are stored in memory as Unicode strings of 5 characters.

#### 2-D Array ####

**Creating a 2D array**
2D array will have 2 dimension as row & columns

In [12]:
#lets us create  2D array
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print(y)
print()

#print the shape of the array
print ("Shape of array: ", y.shape)

#print the size of the array
print ("Size of array: ",y.size)

#print the data type
print("Data type of array element: ",y.dtype)

#print the type of array
print("Object type of array y:",type(y))



[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of array:  (3, 3)
Size of array:  9
Data type of array element:  int32
Object type of array y: <class 'numpy.ndarray'>


**Key notes**

- Numpy will store elements based on the value, if integer it store as int if float stores as float
- if we have both int and float in arrray, numpy will store the element as float. This is called **upcasting**

In [13]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


Even though NumPy automatically selects the dtype of the ndarray, NumPy also allows you to specify the particular dtype you want to assign to the elements of the ndarray. You can specify the dtype when you create the ndarray using the keyword dtype in the np.array() function. Let's see an example:

In [14]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print x
print()
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

The elements in x are of type: int64


**Save & Load Array to/from file**

In [15]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)


# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# We print y
print()
print('y = ', y)
print()

# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)


y =  [1 2 3 4 5]

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


#### Built-in-Functions ####

- np.zero(shape) - create zeros with give shape
- np.ones() - create ones with given shape, we can change the data type of elements by passing the dtype value
- np.full(shape, constant value) - create an ndarray with a specified shape that is full of any number we want

In [7]:
# We create a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

# We create a 3 x 3 ndarray full of ones. 
Y = np.ones((3,3), dtype=int)
# We print X
print()
print('Y = \n', Y)
print()

# We print information about X
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

#we create a full array
Z = np.full((3,4),5)

# We print Z
print()
print('Z = \n', Y)
print()

# We print information about Z
print('Z has dimensions:', Z.shape)
print('Z is an object of type:', type(Z))
print('The elements in Z are of type:', Z.dtype)



X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64

Y = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Y has dimensions: (3, 3)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32

Z = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Z has dimensions: (3, 4)
Z is an object of type: <class 'numpy.ndarray'>
The elements in Z are of type: int32


**Identity Matrix**

- As you will learn later, a fundamental array in Linear Algebra is the *Identity Matrix*.
- An Identity matrix is a square matrix that has only 1s in its main diagonal and zeros everywhere else. 
- The function np.eye(N) creates a square N x N ndarray corresponding to the Identity matrix. 
Since all Identity Matrices are square, the np.eye() function only takes a single integer as an argument

In [10]:
#creating a idenity matrix
X = np.eye(5)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)  


X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


**Diagonal Matrix**


In [11]:
y_diag = np.diag([10,15,20,25])
print(y_diag)


[[10  0  0  0]
 [ 0 15  0  0]
 [ 0  0 20  0]
 [ 0  0  0 25]]


**Arange**

- NumPy also allows you to create ndarrays that have evenly spaced values within a given interval. 
- NumPy's np.arange() function is very versatile and can be used with either one, two, or three arguments
- np.arange(N) i.e *np.arange(5)* - will create a rank 1 ndarray with consecutive integers between 0 and N - 1
- np.arange(start,stop) i.e *np.arange(1,10)* - will create a rank 1 ndarray with evenly spaced values within the half-open interval (start, stop). This means the evenly spaced numbers will **include start but exclude stop.**
- np.arrange(start,stop,step) i.e - np.arange(1,10,2) - will create a rank 1 ndarray with evenly spaced values within the half-open interval (start, stop) with *step* being the distance between two adjacent values

In [13]:
x= np.arange(10)
print(x)

x1 = np.arange(1,10)
print(x1)

x2 = np.arange(1,10,2)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
