## Numpy 
This Note book will have references for all Numpy and related code practise

In [1]:
#import statement
import numpy as np

#### 1-D Array###
**Creating a 1-D Array**

There are several ways to create ndarrays in NumPy. The two ways to create ndarrays:

Using regular Python lists

Using built-in NumPy functions

In this section, we will create ndarrays by providing Python lists to the NumPy *np.array()* function. It is important to remember that np.array() is NOT a class, it is just a function that returns an ndarray

In [5]:
#Let's create a 1D array x
x= np.array([1,2,3,4,5])
print(x)



[1 2 3 4 5]


**Rank:**

1D arrays as rank 1 arrays. In general N-Dimensional arrays have rank N. 
Therefore, we refer to a 2D array as a rank 2 array. 

**Shape, Size and Datatype of Array:**

The shape of an array is the size along each of its dimensions. 
For example, the shape of a rank 2 array will correspond to the *number of rows and columns* of the array. 
The shape attribute returns a tuple of N positive integers that specify the sizes of each dimension. 
In the example below we will see the details of 1-D array created and its shape, its type, and the data-type (dtype) of its elements.

In [7]:
#print the shape of the array
print ("Shape of array: ", x.shape)

#print the size of the array
print ("Size of array: ",x.size)

#print the data type
print("Data type of array: ",x.dtype)

Shape of array:  (5,)
Size of array:  5
Data type of array:  int32


We can see that the shape attribute returns the tuple (5,) telling us that x is of rank 1 (i.e. x only has 1 dimension ) and it has 5 elements. 
The type() function tells us that x is indeed a NumPy ndarray. 
Finally, the .dtype attribute tells us that the elements of x are stored in memory as signed 64-bit integers. Another great advantage of NumPy is that it can handle more data-types than Python lists.

In [9]:
b=np.array(["Apple","Google","Microsoft"])

print()
print(b)
print()

#print the shape of the array
print ("Shape of array: ", b.shape)

#print the size of the array
print ("Size of array: ",b.size)

#print the data type
print("Data type of array: ",b.dtype)


['Apple' 'Google' 'Microsoft']

Shape of array:  (3,)
Size of array:  3
Data type of array:  <U9


dtype attribute tells us that the elements in b are stored in memory as Unicode strings of 5 characters.

#### 2-D Array ####

**Creating a 2D array**
2D array will have 2 dimension as row & columns

In [12]:
#lets us create  2D array
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print(y)
print()

#print the shape of the array
print ("Shape of array: ", y.shape)

#print the size of the array
print ("Size of array: ",y.size)

#print the data type
print("Data type of array element: ",y.dtype)

#print the type of array
print("Object type of array y:",type(y))



[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of array:  (3, 3)
Size of array:  9
Data type of array element:  int32
Object type of array y: <class 'numpy.ndarray'>


**Key notes**

- Numpy will store elements based on the value, if integer it store as int if float stores as float
- if we have both int and float in arrray, numpy will store the element as float. This is called **upcasting**

In [13]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


Even though NumPy automatically selects the dtype of the ndarray, NumPy also allows you to specify the particular dtype you want to assign to the elements of the ndarray. You can specify the dtype when you create the ndarray using the keyword dtype in the np.array() function. Let's see an example:

In [14]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print x
print()
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

The elements in x are of type: int64


**Save & Load Array to/from file**

In [15]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', x)


# We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

# We print y
print()
print('y = ', y)
print()

# We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)


y =  [1 2 3 4 5]

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


#### Built-in-Functions ####

- np.zero(shape) - create zeros with give shape
- np.ones() - create ones with given shape, we can change the data type of elements by passing the dtype value
- np.full(shape, constant value) - create an ndarray with a specified shape that is full of any number we want

In [7]:
# We create a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

# We create a 3 x 3 ndarray full of ones. 
Y = np.ones((3,3), dtype=int)
# We print X
print()
print('Y = \n', Y)
print()

# We print information about X
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

#we create a full array
Z = np.full((3,4),5)

# We print Z
print()
print('Z = \n', Y)
print()

# We print information about Z
print('Z has dimensions:', Z.shape)
print('Z is an object of type:', type(Z))
print('The elements in Z are of type:', Z.dtype)



X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64

Y = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Y has dimensions: (3, 3)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32

Z = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Z has dimensions: (3, 4)
Z is an object of type: <class 'numpy.ndarray'>
The elements in Z are of type: int32


**Identity Matrix**

- As you will learn later, a fundamental array in Linear Algebra is the *Identity Matrix*.
- An Identity matrix is a square matrix that has only 1s in its main diagonal and zeros everywhere else. 
- The function np.eye(N) creates a square N x N ndarray corresponding to the Identity matrix. 
Since all Identity Matrices are square, the np.eye() function only takes a single integer as an argument

In [10]:
#creating a idenity matrix
X = np.eye(5)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)  


X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


**Diagonal Matrix**


In [11]:
y_diag = np.diag([10,15,20,25])
print(y_diag)


[[10  0  0  0]
 [ 0 15  0  0]
 [ 0  0 20  0]
 [ 0  0  0 25]]


**Arange**

- NumPy also allows you to create ndarrays that have evenly spaced values within a given interval. 
- NumPy's np.arange() function is very versatile and can be used with either one, two, or three arguments
- np.arange(N) i.e *np.arange(5)* - will create a rank 1 ndarray with consecutive integers between 0 and N - 1
- np.arange(start,stop) i.e *np.arange(1,10)* - will create a rank 1 ndarray with evenly spaced values within the half-open interval (start, stop). This means the evenly spaced numbers will **include start but exclude stop.**
- np.arrange(start,stop,step) i.e - np.arange(1,10,2) - will create a rank 1 ndarray with evenly spaced values within the half-open interval (start, stop) with *step* being the distance between two adjacent values

In [13]:
x= np.arange(10)
print(x)

x1 = np.arange(1,10)
print(x1)

x2 = np.arange(1,10,2)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


**Linspace**

Even though the np.arange() function allows for non-integer steps, such as 0.3, **the output is usually inconsistent, due to the finite floating point precision**. For this reason, in the cases where non-integer steps are required, it is usually better to use the function np.linspace()

 **np.linspace(start, stop, N)** function returns N evenly spaced numbers over the closed interval (start, stop). This means that both the start and thestop values are included

In [3]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25
X = np.linspace (0,25,10)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)  




X = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

X has dimensions: (10,)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


 - we can see 10 eventualy intervaled numbers between 0 to 25.
 - if need to exclude the last digit, we can by setting the keyword **endpoint = False**

**Reshape**

- np.reshape(ndarray, new_shape)
- Reshape used to convert the 1D to N-D array. 
- The elements in the 1D array shoud match the dimension we input. for example - 1D array with 10 elements can be reshaped as 2D with 5 x 2 or 2 x5 but not 3x4


In [7]:
x = np.arange(50)
print ("original X", x)
print ("shape of x", x.shape)

x=x.reshape(25,2)
print ("Reshaped X", x)
print ("shape of new x", x.shape)

original X [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
shape of x (50,)
Reshaped X [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]]
shape of new x (25, 2)


In [8]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 

# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32

X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


**Random Nd Arrays**

- **np.random.random(shape)** function to create an ndarray of the given shape with random floats in the half-open interval (0.0, 1.0)
- **np.random.randint(start, stop, size = shape)** creates an ndarray of the given shape with random integers in the half-open interval (start, stop)
- **np.random.rand(shape)** will create an array of the given shape and populate it with random samples from a uniform distribution over (0, 1)
- **np.random.normal(mean, standard deviation, size=shape)**
In some cases, you may need to create ndarrays with random numbers that satisfy certain statistical properties for example, creates an ndarray with the given shape that contains random numbers picked from a normal (Gaussian) distribution with the given mean and standard deviation. 
- **np.random.randn(N)** will generates a matrix filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1.

In [10]:
#np.random.random(shape)
X = np.random.random((3,3))
# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.95399281 0.01225931 0.31903071]
 [0.98280078 0.30819832 0.38684034]
 [0.36616898 0.3859594  0.35724233]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [11]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,(3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[ 4 12]
 [10 11]
 [11 13]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [13]:
#We create a 100 x 100 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0,0.1,(100,100))
# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[ 0.02694705  0.04947832 -0.03796749 ...  0.02729805  0.05198602
  -0.17310154]
 [ 0.05205792  0.02349479  0.26439026 ... -0.01095012  0.16664777
  -0.11486625]
 [-0.02468997  0.06961028 -0.03017137 ... -0.06069926 -0.0283256
   0.0976365 ]
 ...
 [ 0.12505832 -0.02593088  0.11265138 ...  0.21870188 -0.08361976
  -0.18012141]
 [ 0.11465266  0.04702692  0.03490346 ... -0.01316394  0.0086452
   0.11324408]
 [-0.01114407 -0.00139915 -0.00291159 ...  0.11343554  0.05561915
  -0.01782706]]

X has dimensions: (100, 100)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 0.0016703335992551331
The maximum value in X is: 0.40278695654831814
The minimum value in X is: -0.37163696787721756
X has 4923 negative numbers
X has 5077 positive numbers


In [14]:
#np.random.rand(shape)
X = np.random.rand(3,3)
# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.15434716 0.21688783 0.05244779]
 [0.83839356 0.56017946 0.79506465]
 [0.04089127 0.49589741 0.92745817]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [15]:
#np.random.randn(N)
X = np.random.randn(10)
# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [-0.46580439 -0.51769515 -1.36502286  0.12805296 -0.11770055  1.02629479
  0.41471195 -0.6559395  -1.30419416  1.04808341]

X has dimensions: (10,)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -0.1809213508641976
The maximum value in X is: 1.0480834144870415
The minimum value in X is: -1.3650228603895365
X has 6 negative numbers
X has 4 positive numbers
